### PR TITLE
update to Theano 1.0.1

### PR DESCRIPTION
**Pull request by slefrancois**

### CODE REVIEW

**Comment by nouiz** [comment]
This seem to build, but I have this strange output. This was probably already a problem. Can you also look at it?

```
Step 30/36 : RUN pip install git+git://github.com/Theano/Theano.git@rel-$THEANO_VERSION
 ---> Running in 55168e1d14c5
Collecting git+git://github.com/Theano/Theano.git@rel-1.0.1
  Cloning git://github.com/Theano/Theano.git (to rel-1.0.1) to /tmp/pip-kdirzi8k-build
Collecting numpy>=1.9.1 (from Theano==1.0.1)
  Downloading numpy-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (17.2MB)
Collecting scipy>=0.14 (from Theano==1.0.1)
  Downloading scipy-1.0.0-cp36-cp36m-manylinux1_x86_64.whl (50.0MB)
Requirement already satisfied: six>=1.9.0 in /opt/conda/lib/python3.6/site-packages (from Theano==1.0.1)
Installing collected packages: numpy, scipy, Theano
  Running setup.py install for Theano: started
    Running setup.py install for Theano: finished with status 'done'
Successfully installed Theano-1.0.1 numpy-1.14.0 scipy-1.0.0
```

Mostly, a few dependency of Theano get installed from pip instead of conda. We need a way to force the installation of those dependency by conda before installing Theano from pip. But why not install Theano from conda directly? Something like:

conda install -c mila-udem theano=THEANO_VERSION pygpu

**Comment by slefrancois** [comment]
I changed the dockerfile to have Theano installed with Conda.

I also had to set `MKL_THREADING_LAYER=GNU`, which seems to be required by the newer Theano and MKL 2018.

**Comment by nouiz** [comment]
$ nvidia-docker run -d -p 8888:8888  -e PASSWORD="123abcChangeThis" theano_secure
6c2c4b96729678b715905b238b637563a6a25e12f7ee5ae19929b051da7043cf
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:381: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.1 --pid=59288 /var/lib/docker/overlay2/b80d5247a78222458f3364bdd1356789532fa7eb10c5b529f59c4ce1bb46a2bd/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: cuda >= 9.1\\\\n\\\"\"": unknown.

**Comment by slefrancois** [comment]
This looks like a machine without a driver compatible with CUDA 9.1. Although docker containerizes the environment, nvidia-docker works by passing the GPU device and driver from the system to the container.

If that's the issue, either we require cuda 9.1 to run the docker, or we downgrade to a lower version.

**Comment by nouiz** [comment]
I changed to CUDA 9.0 instead of 9.1 to be more compatible.

Merging.

**Pull request merged**
